version: '3.8'

services:
  dms-fe:
    build: .
    container_name: datn-fe
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "5173:5173"

