name: Build, Push, Ssh, Pull, Down, Up

on:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  build-and-push:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push FE Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/datn-fe

  pull-and-up:
    name: Pull new image and deploy to Google Cloud
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
      
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      # - name: Copy docker-compose file
      #   run: |
      #     scp -i ~/.ssh/id_rsa docker-compose.yaml ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }}:/home/liinhhnt/
      #     ssh -i ~/.ssh/id_rsa ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} "sudo mv /home/liinhhnt/docker-compose.yaml /home/datn/fe/"

      - name: SSH to GGC and pull new images
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} << 'EOF'
            sudo docker system prune -f
            sudo docker image prune -af
            sudo docker compose -f /home/datn/fe/docker-compose.yaml pull
            sudo docker compose -f /home/datn/fe/docker-compose.yaml down
            sudo docker compose -f /home/datn/fe/docker-compose.yaml up -d
          EOF
